### ISSUE TITLE
on homeassistant 0.1 there is no ui-lovelace.yaml

### ISSUE THREAD

**Issue by zmiguelb** [custom-cards/state-attribute-element#11]
**Version of the cusom_component**
latest

**Describe the bug**
No way to implement on the latest version since there is no ui-lovelace.yaml

**Comment by ludeeus** [comment]
That is just wrong.
If you are running Lovelace in yaml mode that file still exists.
If you you would add the same thing in the raw editor in the UI.

**Comment by zmiguelb** [comment]
Thks.
btw it is a really nice feature, well done for the good work
