### ISSUE TITLE
If attribute value is boolean false, it shows as 'does not exist in entity'.

### ISSUE THREAD

**Issue by jgrieger1** [custom-cards/state-attribute-element#12]
**Version of the cusom_component**
latest

**Describe the bug**
As a result of #10, if an attribute's value is boolean false, 'Attribute does not exist in entity' is displayed instead of the value of 'false'.

Changing:
https://github.com/custom-cards/state-attribute-element/blob/af633ab736fcddd6ca127aae3223ee22d095c439/state-attribute-element.js#L14
To:
`if (this.state || this.state === false) {`

fixes this issue.

**Comment by ludeeus** [comment]
Please add a PR with it 👍
