### ISSUE TITLE
I'm getting an error

### ISSUE THREAD

**Issue by abeksis** [custom-cards/state-attribute-element#4]
http://192.168.1.3:8123/local/state-attribute-element.js?v=0:7:41 Uncaught TypeError: Cannot read property 'attributes' of undefined

what could it be? Please help

**Comment by ciotlosm** [comment]
Your element probably is wrong. Check for typos

**Comment by abeksis** [comment]
I do not see any problem. You can direct me? :(

**Comment by ciotlosm** [comment]
You would need to post your config in the issue. Also the `dev-info` panel detailed state output for the entity you are trying to use.

**Comment by abeksis** [comment]
my Lovelace:
https://paste.ofcode.org/3bUSb7xreXDQYKL3mWdK5Pq

I'm sorry I do not know what this means dev-info

**Comment by abeksis** [comment]
I try to apply this possibility

https://sharethelove.io/cards/tautulli-card

**Comment by ciotlosm** [comment]
Did you install https://github.com/custom-components/sensor.tautulli ? Looks like maybe 1st sensor is different from the docs:

```
            entity: sensor.tautulli__ludeeus
            attribute: magic_title
```

**Comment by abeksis** [comment]
```yaml
entity: sensor.tautulli__ludeeus
attribute: magic_title
```

At first it was like this, I tried to change maybe the problem will disappear .. but it does not help.

**Comment by ludeeus** [comment]
Unless you have a user named 'ludeeus' on your tautulli server the sensor name will be different from that, check the dev-states to get the correct sensor entity.

**Comment by abeksis** [comment]
It's the only users I have
https://imgur.com/a/zcjuYJy

**Comment by ludeeus** [comment]
Then use:
```yaml
entity: sensor.tautulli__abeksis
attribute: magic_title
```
and not:
```yaml
entity: sensor.tautulli__ludeeus
attribute: magic_title
```

**Comment by abeksis** [comment]
Thanks wonderful works

https://imgur.com/a/tPJUSyl
