### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by abeksis** [custom-cards/state-attribute-element#6]
2018-10-01 08:32:56 ERROR (MainThread) [frontend.js.latest.201809270] https://ip/local/state-attribute-element.js?v=2.1:10:14 TypeError: undefined is not an object (evaluating 'state.length')

**Comment by ludeeus** [comment]
Can you post the configuration you have for this element?
And verify in /dev-states that you are using the correct entity id.

**Comment by abeksis** [comment]
`      - type: picture-elements
        image: /local/lovelace/tv/plex.png
        elements:
          - type: custom:text-element
            text: "<b style='color: orange; font-size: 18px'>Now Playing: </b>"
            style:
              top: 7%
              left: 15px
              transform: none
          - type: custom:state-attribute-element
            entity: sensor.tautulli__abeksis 
            attribute: magic_title
            show_empty: false
            style:
              top: 20%
              left: 15px
              font-size: 16px
              color: white
              transform: none
          - type: custom:text-element
            text: "<b style='color: orange; font-size: 18px'>Statistics: </b>"
            style:
              top: 47%
              left: 15px
              transform: none
          - type: custom:state-attribute-element
            entity: sensor.tautulli
            attribute: Movie
            show_empty: true
            prefix: "<b style='color: orange; margin-right: 5px'>Most played movie: </b>"
            style:
              top: 60%
              left: 15px
              color: white
              transform: none
          - type: custom:state-attribute-element
            entity: sensor.tautulli
            attribute: TV
            show_empty: true
            prefix: "<b style='color: orange; margin-right: 11px'>Most played show: </b>"
            style:
              top: 70%
              left: 15px
              color: white
              transform: none
          - type: custom:state-attribute-element
            entity: sensor.tautulli
            attribute: User
            show_empty: true
            prefix: "<b style='color: orange; margin-right: 20px'>Most active user: </b>"
            style:
              top: 80%
              left: 15px
              color: white
              transform: none``

**Comment by ludeeus** [comment]
Does both `sensor.tautulli__abeksis` and `sensor.tautulli` exist?
