### ISSUE TITLE
Error in log when device unavailable

### ISSUE THREAD

**Issue by bosbefok** [custom-cards/state-attribute-element#7]
**Version of the cusom_component**
0.1.0

**Describe the bug**
Sometimes an entity being used becomes unavailable and this custom card throws the following error in HA log. Perhaps this error can be caught and handled elegantly.

**log**
Log Details (ERROR)
Thu Oct 18 2018 19:44:19 GMT+1000 (Australian Eastern Standard Time)

http://192.168.86.27:8123/local/custom-lovelace/state-attribute-element/state-attribute-element.js?v=0.1.0:10:15 Uncaught TypeError: Cannot read property 'length' of undefined

**Comment by ludeeus** [comment]
I have not seen this issue before now, sorry about that...
This would be cool, do you have an idea of how one would do that? :D
