### ISSUE TITLE
Add tap-action configuration variable

### ISSUE THREAD

**Issue by pmontgo33** [custom-cards/state-attribute-element#8]
**Is your feature request related to a problem? Please describe.**
Using this custom-card I have successfully swapped my climate thermostat icons for the temperatures, which is a much more useful way to view them on a floorplan. What I am missing, however, is the ability to click on the text of the attribute displayed, and be provided with the more_info screen.

**Describe the solution you'd like**
Add tap_action and hold_action as configuration variables.

**Describe alternatives you've considered**
I have thought of having the state-icon directly next to the temperature so that I can click that for the more_info screen.

**Additional context**
None.

**Comment by ludeeus** [comment]
I must disappoint you here, I do not know enough about frontend to get this added.
